# Generated by Django 5.0.1 on 2024-01-11 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo del articulo')),
                ('texto', models.TextField(verbose_name='Contenido del articulo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotos', verbose_name='Foto')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación del articulo')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación del articulo')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentario del articulo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación del comentario')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación del comentario')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.articulo')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
