# Generated by Django 5.0.1 on 2024-01-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_jugador_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='responable',
            new_name='responsable',
        ),
    ]
