# Generated by Django 5.0.1 on 2024-01-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_rename_responable_equipo_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos', verbose_name='Foto'),
        ),
    ]
