# Generated by Django 5.0.1 on 2024-02-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_equipo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del Jugador'),
        ),
    ]
