# Generated by Django 5.0.1 on 2024-02-08 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_jugador_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competicion',
            name='responsable',
            field=models.ForeignKey(default='kras', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipo',
            name='competicion',
            field=models.ManyToManyField(related_name='equipos', to='principal.competicion', verbose_name='Competicion'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='principal.equipo'),
        ),
    ]
