# Generated by Django 5.0.1 on 2024-01-18 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre de la categoría')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción de la categoría')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion del artículo')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de ultima modificación del artículo')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título del artículo')),
                ('texto', models.TextField(verbose_name='Contenido del artículo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotos', verbose_name='Foto del artículo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion del artículo')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de ultima modificación del artículo')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categorias', models.ManyToManyField(to='principal.categoria', verbose_name='Categorías')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentario del artículo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion del comentario')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de ultima modificación del comentario')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.articulo')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
